QuizCreateApp/Models/ErrorViewModel.cs
namespace QuizCreateApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QuizCreateApp/Controllers/AccountController.cs
using Businness.Model;
using Businness.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace QuizCreateApp.Controllers
{
    public class AccountController : Controller
    {
        IAccountService _accountService;
        public AccountController(IAccountService accountService)
        {
            _accountService = accountService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginModel loginModel)
        {
            var userToLogin = _accountService.Login(loginModel);
            if (!userToLogin.isSuccess)
            {
                loginModel.ErrorMessage = userToLogin.message;
                return View("Index", loginModel);
            }
            var claims = new List<Claim>();

            claims.Add(new Claim(ClaimTypes.Name, loginModel.Email));
            claims.Add(new Claim("userid", userToLogin.Data.Id.ToString()));

            var userIdentity = new ClaimsIdentity(claims, "login");

            ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

            await HttpContext.SignInAsync(principal);

            return RedirectToAction("QuizList", "Home");
        }

        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(UserRegisterModel userRegisterModel)
        {
            var userExists = _accountService.UserExists(userRegisterModel.Email);
            if (!userExists.isSuccess)
            {
                userRegisterModel.ErrorMessage = userExists.message;
                return View("Register", userRegisterModel);
            }

            var registerResult = _accountService.Register(userRegisterModel, userRegisterModel.Password);

            if (registerResult.isSuccess)
            {
                userRegisterModel.IsSuccess = true;
                return View("Register", userRegisterModel); 
            }
            else
            {
                userRegisterModel.ErrorMessage = registerResult.message;
                return View("Register", userRegisterModel);
            }

        }
    }
}

QuizCreateApp/Controllers/ExamController.cs
using Businness.Model;
using Businness.Services;
using Core.Utilities.Results;
using Microsoft.AspNetCore.Mvc;

namespace QuizCreateApp.Controllers
{
    public class ExamController : Controller
    { 
        IExamService _examService;
        public ExamController(IExamService examService)
        { 
            _examService = examService;
        }

        [Route("test")]
        public IActionResult Index()
        { 
            return View();
        }

        [HttpGet]
        public List<ExamModel> SelectAllExam()
        {
            var allExam = _examService.GetAll().Data;

            return allExam;
        }

        [HttpPost]
        public IDataResult<List<CompleteExamResponse>> CompleteExam(CompleteExamRequestMaster obj)
        {
            return _examService.CompleteExam(obj);
        }
    }
}

QuizCreateApp/Controllers/HomeController.cs
using Businness.Model;
using Businness.Services;
using Core.Entities.Concrete;
using Core.Utilities.Results;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuizCreateApp.Models;
using System.Diagnostics;
using System.Security.Claims;

namespace QuizCreateApp.Controllers
{

    [Authorize]
    public class HomeController : Controller
    { 

        IBlogSelectService _blogSelectService;
        IQuizService _quizService;
        IUserService _userService;
        public HomeController(IBlogSelectService blogSelectService, IQuizService quizService, IUserService userService)
        {
            _blogSelectService = blogSelectService;
            _quizService = quizService;
            _userService = userService;
        } 
        public IActionResult QuizList()
        {
            int userid = int.Parse(User.Claims.Where(c => c.Type == "userid").Select(c => c.Value).SingleOrDefault());
            var quizList = _quizService.GetAllFromUser(userid);

            return View(quizList.Data);
        }

        [Route("createquiz")]
        public IActionResult CreateQuiz()
        {
 
            return View();
        }


        [Route("deletequiz")]
        [HttpPost]
        public Core.Utilities.Results.IResult DeleteQuiz(int quizId)
        {
            var quizObj = new Quiz
            {
                Id = quizId,
            };
            _quizService.Delete(quizObj);
            return new SuccessResult();
        }
        [HttpGet]
        public IDataResult<List<NewsContentModel>> getItems()
        {
            var latestPosts = _blogSelectService.GetLatestNews();

            return latestPosts;
        }

        [HttpPost]
        public Core.Utilities.Results.IResult InsertNewQuiz(QuizRequestModel quiz)
        {
            int userid = int.Parse(User.Claims.Where(c => c.Type == "userid").Select(c => c.Value).SingleOrDefault());
             
            _quizService.SaveQuiz(quiz, userid);
            return new SuccessResult();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

QuizCreateApp/Views/Exam/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ExamLayout.cshtml";
}


<input type="hidden" id="selectAllExamId" value="@Url.Action("SelectAllExam", "Exam")" />
<input type="hidden" id="completeExamurlId" value="@Url.Action("CompleteExam", "Exam")" />


<div class="container">

    <div class="row" id="prevnextexam">
        <a class="col-2" onclick="goToPrevExam()">
            <img src="@Url.Content("~/images/back-arrow.png")" width="30" height="30" />
        </a>
        <a class="col-2"  onclick="goToNextExam()">
            <img src="@Url.Content("~/images/right-arrows.png")" width="30" height="30" />
        </a>
    </div>
    <div id="examcontainer">
    </div>



    <div class="text-center mt-4">
        <button class="btn-primary btn btn-lg" id="completequizbutton" onclick="completeExam()">
            Complete the Quiz
        </button>
    </div>
</div>


<script src="@Url.Content("~/js/exam.js")"></script>


<link rel="stylesheet" href="@Url.Content("~/css/exam.css")" asp-append-version="true" />
 

QuizCreateApp/Views/Home/CreateQuiz.cshtml
@{
    ViewData["Title"] = "CreateQuiz";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<input type="hidden" id="quizPosturl" value="@Url.Action("InsertNewQuiz", "Home")" />
<input type="hidden" id="blogselectApi" value="@Url.Action("getItems", "Home")" />
<input type="hidden" id="homePageUrl" value="@Url.Action("QuizList", "Home")" />
<div class="container">

    <div class="input-group mb-3">
        <label class="form-check-label" for="exampleCheck1">Blog Title</label>
        <select class="custom-select w-100" id="blogTitleSelect" onchange="ontitlechange()">
            <option disabled selected value="">Choose Blog...</option>

        </select>
    </div>
    <div class="input-group mb-3">
        <label class="form-check-label" for="exampleCheck1">Blog Content</label>
        <div id="blog-content" class="blog-content">
            <div class="text-center">
                Please select a title for the Blog Post to appear.
            </div>
        </div>
    </div>

    <div id="question-area">

        
       
    </div>


    <div class="text-center mt-4">
        <button class="btn-primary btn btn-lg" onclick="onPostQuestion()">
            Save Quiz
        </button>
    </div>
</div>


<script src="@Url.Content("~/js/quizCreate.js")"></script>
<link rel="stylesheet" href="@Url.Content("~/css/createQuiz.css")" asp-append-version="true" />

QuizCreateApp/Views/Home/QuizList.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<Entities.Concrete.Quiz>



    <input type="hidden" value="@Url.Action("DeleteQuiz","Home")" id="deleteQuizUrl" />
@if (Model.Count > 0)
{
    <div class="text-right">
    <a class="btn btn-success" href="@Url.Action("CreateQuiz", "Home")">Add Quiz</a>

    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">CreatinDate</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Title</td>
                <td>@item.Creatindate.ToShortDateString()</td>
                <td>
                    <a onclick="deleteQuiz(@item.Id)" class="text-danger">
                        delete
                    </a>
                </td>
            </tr>
            }
        </tbody>
    </table>


}
else
{
    <div class="text-center">
        <h1 class="display-4">Welcome to Quiz Creation App.</h1>
        <p>There is no quiz yet <a href="@Url.Action("CreateQuiz")">Click and create quiz</a>.</p>
    </div>
}


<script src="@Url.Content("~/js/quizList.js")"></script>

QuizCreateApp/Views/Shared/Components/CommonImport/Default.cshtml
 


 <link rel="stylesheet" href="@Url.Content("~/lib/bootstrap/dist/css/bootstrap.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/site.css")" asp-append-version="true" />
    <link rel="stylesheet" href="@Url.Content("~/QuizCreateApp.styles.css")" asp-append-version="true" />
        <script src="@Url.Content("~/lib/jquery/dist/jquery.min.js")"></script>
    <script src="@Url.Content("~/lib/bootstrap/dist/js/bootstrap.bundle.min.js")"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

       <script>

            function showLoading(){
            var loadingOverlay = document.querySelector('.loading');
            loadingOverlay.classList.remove('hidden');
         }
             function hideLoading(){
            var loadingOverlay = document.querySelector('.loading');
            loadingOverlay.classList.add('hidden');
        }
    </script>

        <script src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

QuizCreateApp/Views/Shared/_ExamLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - QuizCreateApp</title>

    @await Component.InvokeAsync("CommonImport")

</head>
<body>
    <div class="loading hidden">
        <div class='uil-ring-css' style='transform:scale(0.79);'>
            <div></div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>


</body>
</html>

QuizCreateApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuizCreateApp</title>

    @await Component.InvokeAsync("CommonImport")

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="QuizList">QuizCreateApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="QuizList">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CreateQuiz">Create Quiz</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exam" asp-action="Index">Go To Exam</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="loading hidden">
        <div class='uil-ring-css' style='transform:scale(0.79);'>
            <div></div>
        </div>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>


    @await RenderSectionAsync("Scripts", required: false);



</body>
</html>

QuizCreateApp/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head> 
    <title>@ViewData["Title"]</title>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>

	<link rel="stylesheet" type="text/css" href="@Url.Content("~/vendor/bootstrap/css/bootstrap.min.css")">
												 
	<link rel="stylesheet" type="text/css" href="@Url.Content("~/fonts/font-awesome-4.7.0/css/font-awesome.min.css")">
											 
	<link rel="stylesheet" type="text/css" href="@Url.Content("~/fonts/Linearicons-Free-v1.0.0/icon-font.min.css")">
												 
	<link rel="stylesheet" type="text/css" href="@Url.Content("~/vendor/animate/animate.css")">
												 
	@*<link rel="stylesheet" type="text/css" href="@Url.Content("~/vendor/css-hamburgers/hamburgers.min.css")">*@
											 
	@*<link rel="stylesheet" type="text/css" href="@Url.Content("~/vendor/animsition/css/animsition.min.css")">*@
											 
	@*<link rel="stylesheet" type="text/css" href="@Url.Content("~/vendor/select2/select2.min.css")">*@

	@*<link rel="stylesheet" type="text/css" href="@Url.Content("~/vendor/daterangepicker/daterangepicker.css")">*@

	<link rel="stylesheet" type="text/css" href="@Url.Content("~/css/login/util.css")">
	<link rel="stylesheet" type="text/css" href="@Url.Content("~/css/login/main.css")">

</head>
<body>
    <div>
        @RenderBody()
    </div>

	<script src="@Url.Content("~/vendor/jquery/jquery-3.2.1.min.js")"></script>

	@*<script src="@Url.Content("~/vendor/animsition/js/animsition.min.js")"></script>*@

	@*<script src="@Url.Content("~/vendor/bootstrap/js/popper.js")"></script>*@
	<script src="@Url.Content("~/vendor/bootstrap/js/bootstrap.min.js")"></script>
@*
	<script src="@Url.Content("~/vendor/select2/select2.min.js")"></script>

	<script src="@Url.Content("~/vendor/daterangepicker/moment.min.js")"></script>
	<script src="@Url.Content("~/vendor/daterangepicker/daterangepicker.js")"></script>

	<script src="@Url.Content("~/vendor/countdowntime/countdowntime.js")"></script>*@
</body>
</html>